### ISSUE TITLE
Clearer introduction

### ISSUE THREAD

**Issue by arturmuller** [saamo/api-blueprint-focus-booster#1]
The first time I was reading the intro it wasn't really clear to me what this *is*. I think saying it is a *boilerplate*, *bootstrap*, *starter kit*, whatever... might make it a lot easier for people to grok what this is about and whether they want to use it.

**Comment by saamo** [comment]
I would have thought that people who were familiar with API Blueprints and especially people who used Apiary.io and dealt with the problem this tool tried to solve would have known what it was about (they're the target group). But since it wasn’t clear even to you, I might reconsider it and try to introduce it better!

The problem is that it's not a boilerplate (you don't need this structure to produce the blueprint), neither a starter kit or a bootstrap (same reasons). You only need some text editor to produce the blueprint (if you’re a sadist of course).

I would say that it's kind of "environment" (I didn't come up with anything better) which helps you to organize and maintain the blueprint by splitting it into smaller parts, validating payloads, using template variables, etc.

**Comment by arturmuller** [comment]
Right. I'm sure some people will get it just fine if they have the context, but I figured that for others who find it, let's say, accidentally, it might be a bit confusing. So it's kinda about what you think is more likely.

Anyways, about **what it is**: I think you could say that — *if you are masochist* — you can produce anything on the web with just a couple of huge files and no structure. But people don't, because mostly they want their workflow to be nice and pleasant. I think those that are looking to have a pleasant workflow usually try to find inspiration from various starter packs, kits and boilerplates. And after thinking about this for a while I think this *is* a boilerplate. (When you check other boilerplate repos, they seem to do similar stuff...)

In my eyes, all that it needs, is to change this intro sentence:
> API Blueprint Focus Booster helps you when working with API Blueprints.

to something more specific like this:
> API Blueprint Focus Booster is a boilerplate template which helps you work effectively on large API Blueprints.

...and maybe change the short description to:
> Boilerplate for efficiently writing large API Blueprints

**Comment by saamo** [comment]
I'm still not convinced that this is a boilerplate. IMO a boilerplate kicks you at the start. It does something for you which you would be doing _anyways_ and very often repetitively (like writing HTML5 markup when creating HTML5 page which [this boilerplate](https://html5boilerplate.com) does for you because you would write it anyway). This is not the case – you don't need anything from this repo to produce the blueprint.

But I guess it depends only on a perspective because when I read your proposed text changes, they kinda make sense to me. Maybe because the boilerplate word includes _feeling of help_ implicitly and that's what this is all about – helping you with API Blueprints :)

**Comment by arturmuller** [comment]
Right. Ok, I understand what you mean and you are right. This is not a boilerplate. Well then maybe it's a starter kit? Productivity pack? Or maybe the obvious should win: 'a collection of gulp plugins'?

**Comment by saamo** [comment]
‘Productivity pack’ fits better when you think of it as a product. But I really like ‘collection of gulp plugins’ because this is what it really is. Also including word ‘Gulp’ gives you a quite good hint what to expect.

Or maybe I would change it to ‘collection of Gulp tasks’ which I think is even more appropriate in this case because it implies by default that they work together to achieve something (‘collection of Gulp plugins’ could be seen only as a bunch of useful plugins).

> Gulp tasks for efficiently writing large API Blueprints

> API Blueprint Focus Booster is a collection of Gulp tasks which helps you work effectively on large API Blueprints.

**Comment by arturmuller** [comment]
Yup, I think 'collection of Gulp tasks' nails it. Last thing: I would maybe move the 'efficiency' to the end of the sentence as that is where it has most impact (and efficiency is what the collection is about, right?) So that would be:

> Gulp tasks for writing large API Blueprints efficiently

> API Blueprint Focus Booster is a collection of Gulp tasks which help you write large API Blueprints efficiently.

(also note it's 'help' not 'helps' as you are referring to the tasks not the collection any more.

**Comment by saamo** [comment]
Updated. Thank you!
